Bootstrap: docker
From: mambaorg/micromamba:1.3.1

%files
	environment.yml /environment.yml

%post
	## Install dependencies with mamba
	micromamba create -n porefile -y -f /environment.yml && \
		micromamba clean --all --yes

%environment
	export PATH="/opt/conda/envs/porefile/bin:$PATH"

%labels
	Authors: Cecilia Salazar (csalazar@pasteur.edu.uy) & Ignacio Ferres (iferres@pasteur.edu.uy)
	Maintainer: Ignacio Ferres (iferres@pasteur.edu.uy)
